#!/bin/sh #xsh

candidate="${1:-java}"

for platform in darwinx64 darwinarm64 mingw64_nt_10 linuxarm64 linuxx64 ; do
    all_url="https://api.sdkman.io/2/candidates/${candidate}/${platform}/versions/all"
    printf "\n%s\n" "Downloading $platform"

    mkdir -p "sdk/${candidate}/${platform}/pre"
    mkdir -p "sdk/${candidate}/${platform}/post"
    mkdir -p "sdk/${candidate}/${platform}/headers"

    # curl --silent "$all_url" | awk 'BEGIN{ RS=","; FS="-" } map[$2] != 1 { map[$2] = 1 ;print $0}' \
    curl --silent "$all_url" | awk 'BEGIN{ RS=","} { print $0 }' \
    | while read -r version ; do
        printf "%s\n" "Version: $version"
        curl --silent --location "https://api.sdkman.io/2/hooks/pre/$candidate/${version}/${platform}" > "sdk/${candidate}/${platform}/pre/pre-${version}.sh" &
        curl --silent --location "https://api.sdkman.io/2/hooks/post/$candidate/${version}/${platform}" > "sdk/${candidate}/${platform}/post/post-${version}.sh" &
        curl --silent -I "https://api.sdkman.io/2/broker/download/$candidate/${version}/${platform}" > "sdk/${candidate}/${platform}/headers/headers-${version}.txt"
    done
done